/**
 * Barrel shim — re-exports the trimmed store surface.
 *
 * Prefer importing from `@/store` (this shim) rather than reaching into
 * `./store/*` directly, so the public API stays small and stable.
 */

export type { ProjectFileData, ProjectSettings } from './store/helpers';
export {
  DEFAULT_AUTO_ZOOM,
  DEFAULT_BROLL,
  DEFAULT_FILLER_REMOVAL,
  DEFAULT_HOOK_TITLE_OVERLAY,
  DEFAULT_PIPELINE,
  DEFAULT_PROCESSING_CONFIG,
  DEFAULT_PROMO,
  DEFAULT_REHOOK_OVERLAY,
  DEFAULT_RENDER_QUALITY,
  DEFAULT_SETTINGS,
  DEFAULT_TARGET_AUDIENCE,
  PROJECT_SCHEMA_VERSION,
  updateItemById,
} from './store/helpers';
export type { ClipUndoEntry, UndoableSnapshot } from './store/history-slice';
export { useStore, withoutDirtyTracking } from './store/index';
export { selectActiveClips } from './store/selectors';
export type {
  AppSettings,
  AppState,
  BRollDisplayMode,
  BRollSettings,
  BRollTransition,
  CaptionAnimation,
  CaptionBackgroundBox,
  CaptionEmphasisStyle,
  CaptionShadowStyle,
  CaptionStyleSchema,
  CaptionSupersizeStyle,
  ClipBoundary,
  ClipCandidate,
  ClipEndMode,
  ClipRenderSettings,
  CropRegion,
  CropRegionSource,
  CropTimelineEntry,
  CuriosityClipCandidate,
  CuriosityGap,
  EncodingPreset,
  ErrorLogEntry,
  FaceDetectionProgress,
  FillerRemovalSettings,
  FillerSegmentUI,
  HookTitleOverlaySettings,
  HookTitleStyle,
  OutputAspectRatio,
  OutputFormat,
  OutputResolution,
  PartInfoUI,
  PipelineProgress,
  PipelineStage,
  ProcessingConfig,
  PromoSettings,
  PythonSetupState,
  RehookOverlaySettings,
  RehookStyle,
  RenderProgress,
  RenderQualityPreset,
  RenderQualitySettings,
  ScoredSegment,
  ScoringProgress,
  ScoringResult,
  SegmentTimestamp,
  ShotBreakReason,
  ShotSegment,
  ShotSegmentationResult,
  SourceRange,
  SourceVideo,
  StitchedClipCandidate,
  StitchedClipRole,
  TargetDuration,
  TextCase,
  TranscriptionData,
  TranscriptionResult,
  WordAnimationType,
  // Re-exported shared types
  WordTimestamp,
  ZoomIntensity,
  ZoomMode,
  ZoomSettings,
} from './store/types';
