/**
 * fit-text — a defensive responsive-text layer for content blocks.
 *
 * Block copy (headings, kickers, list rows, labels, quotes, definitions, tweet
 * bodies…) is generated by Gemini and is NOT length-bounded, so a long string
 * can overflow the card/canvas at 1920×1080. This module guarantees it never
 * does, using two cooperating mechanisms:
 *
 *   1. A deterministic *character-count* heuristic (`computeFitFontSize`) that
 *      shrinks the font size — never above the design size, never below a floor
 *      — until the text is estimated to fit within a width + line budget.
 *   2. A CSS *line-clamp* backstop (`clampStyle`) plus *break-word* wrapping
 *      (`breakWordStyle`) so any residual overflow (long single words, an
 *      under-estimate) is hard-clipped with an ellipsis instead of bleeding out.
 *
 * Why a heuristic and not measured layout? These compositions render frame by
 * frame in headless Chromium. A measure-then-resize pass (useState + effect)
 * would settle on different frames and *jitter* the size across the render.
 * The heuristic is a pure function of the text, so every frame agrees.
 *
 * No CSS transitions/animations are used — they are inert in a rendered frame.
 * Sizing is static per render.
 */
import type React from 'react';

/* ------------------------------------------------------------------ */
/*  Width / line estimation                                            */
/* ------------------------------------------------------------------ */

/**
 * Average glyph advance as a fraction of the font size, per font family. Used
 * to convert a pixel width budget into an approximate characters-per-line.
 * These are deliberately a touch generous (slightly wide) so the heuristic
 * errs toward shrinking early rather than overflowing.
 */
export const CHAR_WIDTH_RATIO = {
  /** Bebas Neue — condensed all-caps display. */
  bebas: 0.42,
  /** Geist — humanist sans (bold runs a little wider). */
  geist: 0.54,
  /** Instrument Serif italic — pull quotes. */
  serif: 0.46,
  /** JetBrains Mono — fixed pitch. */
  mono: 0.6,
} as const;

/** Estimate how many lines `text` needs when wrapped at `charsPerLine`. */
export function estimateLines(text: string, charsPerLine: number): number {
  if (charsPerLine <= 0) return Number.POSITIVE_INFINITY;
  const words = text.trim().split(/\s+/).filter(Boolean);
  if (words.length === 0) return 1;

  let lines = 1;
  let col = 0;
  // Account for a word that is itself wider than a line (break-word wraps it).
  const placeLongWord = (w: number): void => {
    const extra = Math.ceil(w / charsPerLine);
    lines += extra - 1;
    col = w % charsPerLine || charsPerLine;
  };

  for (const word of words) {
    const w = word.length;
    if (col === 0) {
      if (w <= charsPerLine) col = w;
      else placeLongWord(w);
    } else if (col + 1 + w <= charsPerLine) {
      col += 1 + w;
    } else {
      lines++;
      if (w <= charsPerLine) col = w;
      else placeLongWord(w);
    }
  }
  return lines;
}

export interface FitOptions {
  /** Pixel width budget the text must fit within. */
  maxWidth: number;
  /** Ideal (design) font size — the result never exceeds this. */
  maxFontSize: number;
  /** Smallest allowed font size — the result never drops below this. */
  minFontSize: number;
  /** Hard cap on rendered lines. */
  maxLines: number;
  /** Average glyph advance as a fraction of font size (see CHAR_WIDTH_RATIO). */
  charWidthRatio?: number;
  /** Extra per-character advance in px (e.g. letter-spacing). */
  letterSpacing?: number;
  /** Search decrement in px. */
  step?: number;
}

/**
 * Largest font size in `[minFontSize, maxFontSize]` at which `text` is
 * estimated to fit within `maxWidth` × `maxLines`. Returns `minFontSize` when
 * nothing fits (the CSS clamp then trims the overflow). Pure & deterministic.
 */
export function computeFitFontSize(text: string, opts: FitOptions): number {
  const {
    maxWidth,
    maxFontSize,
    minFontSize,
    maxLines,
    charWidthRatio = CHAR_WIDTH_RATIO.geist,
    letterSpacing = 0,
    step = 2,
  } = opts;

  const floor = Math.min(minFontSize, maxFontSize);
  if (!text || maxWidth <= 0) return maxFontSize;

  for (let size = maxFontSize; size > floor; size -= step) {
    const charWidth = size * charWidthRatio + letterSpacing;
    const charsPerLine = Math.max(1, Math.floor(maxWidth / charWidth));
    if (estimateLines(text, charsPerLine) <= maxLines) return size;
  }
  return floor;
}

/* ------------------------------------------------------------------ */
/*  CSS helpers                                                         */
/* ------------------------------------------------------------------ */

/**
 * Multi-line ellipsis clamp. Combined with a width budget this hard-caps the
 * vertical extent of a text field so it can never push past the card.
 */
export function clampStyle(maxLines: number): React.CSSProperties {
  if (maxLines <= 0) return {};
  return {
    display: '-webkit-box',
    WebkitBoxOrient: 'vertical',
    WebkitLineClamp: maxLines,
    overflow: 'hidden',
    // `minWidth: 0` lets the box shrink inside flex parents instead of
    // forcing the row wider; without it a long word would blow out the width.
    minWidth: 0,
  };
}

/** Break overlong words across lines instead of overflowing the width. */
export const breakWordStyle: React.CSSProperties = {
  overflowWrap: 'break-word',
  wordBreak: 'break-word',
};

/* ------------------------------------------------------------------ */
/*  <FitText> component                                                 */
/* ------------------------------------------------------------------ */

export interface FitTextProps {
  /** The (single string) text to render. */
  children: string;
  /** Pixel width budget the text must fit within. */
  maxWidth: number;
  /** Ideal (design) font size in px — the result never exceeds this. */
  maxFontSize: number;
  /** Smallest allowed font size in px (defaults to 55% of maxFontSize). */
  minFontSize?: number;
  /** Hard line cap + CSS clamp backstop (default 2). */
  maxLines?: number;
  /** Average glyph advance as a fraction of font size (see CHAR_WIDTH_RATIO). */
  charWidthRatio?: number;
  /** Extra per-character advance in px (e.g. letter-spacing). */
  letterSpacing?: number;
  /** Search decrement in px. */
  step?: number;
  /** Style applied to the text box. `fontSize` here is treated as the design max. */
  style?: React.CSSProperties;
  className?: string;
}

/**
 * A text box that deterministically shrinks its font size (down to a floor) to
 * fit a width + line budget, then hard-clamps any residual overflow with an
 * ellipsis. At normal lengths it renders at `maxFontSize`, leaving the design
 * untouched; it only "kicks in" when the copy is long.
 */
export const FitText: React.FC<FitTextProps> = ({
  children,
  maxWidth,
  maxFontSize,
  minFontSize,
  maxLines = 2,
  charWidthRatio,
  letterSpacing,
  step,
  style,
  className,
}) => {
  const floor = minFontSize ?? Math.round(maxFontSize * 0.55);
  const fontSize = computeFitFontSize(children, {
    maxWidth,
    maxFontSize,
    minFontSize: floor,
    maxLines,
    ...(charWidthRatio !== undefined ? { charWidthRatio } : {}),
    ...(letterSpacing !== undefined ? { letterSpacing } : {}),
    ...(step !== undefined ? { step } : {}),
  });

  return (
    <div
      className={className}
      style={{
        ...style,
        fontSize,
        maxWidth,
        ...breakWordStyle,
        ...clampStyle(maxLines),
      }}
    >
      {children}
    </div>
  );
};
